# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - task: run
    silent: true

  build:
    desc: builds .go files and puts the binary in a build folder
    deps:
      - build:main
    cmds:
      - echo Build Complete!
 

  build:main:
    desc: builds main.go and puts the binary in a build folder
    cmds:
      - echo building main.go...
      - go build -v -o ./builds/ cmd/bmiCalculator/main.go

  run:
    desc: runs main.go
    cmds:
      - echo Running main.go
      - go run cmd/bmiCalculator/main.go
    silent: true 

  runbuild:
    desc: runs build of program
    cmds:
      - echo Running main.go
      - go run ./main
    silent: true 
  
  deletebuilds:
    desc: deletes built binaries from build folder
    cmds:
      - rm -r ./builds/
      - echo Builds folder deleted!